"""unique code in company

Revision ID: cd7fd489e81f
Revises: 4415e8fbf1e9
Create Date: 2025-12-11 12:59:11.708567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7fd489e81f'
down_revision: Union[str, Sequence[str], None] = '4415e8fbf1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('unique_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_companies_unique_code'), 'companies', ['unique_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_unique_code'), table_name='companies')
    op.drop_column('companies', 'unique_code')
    # ### end Alembic commands ###
